"""initial schema

Revision ID: 8f7acb0318a9
Revises: 
Create Date: 2026-05-30 01:50:05.801108
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7acb0318a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('restaurant', 'canteen', 'hostel', 'event', name='donor_type', native_enum=False), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donors_type'), ['type'], unique=False)

    op.create_table('recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('ngo', 'shelter', 'community_kitchen', name='recipient_type', native_enum=False), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipients_type'), ['type'], unique=False)

    op.create_table('donation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('servings_donated', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('cooked', 'bakery', 'produce', 'packaged', name='food_category', native_enum=False), nullable=False),
    sa.CheckConstraint('servings_donated >= 0', name='ck_history_servings_nonneg'),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donation_history', schema=None) as batch_op:
        batch_op.create_index('ix_history_donor_date', ['donor_id', 'date'], unique=False)

    op.create_table('food_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('food_type', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('cooked', 'bakery', 'produce', 'packaged', name='food_category', native_enum=False), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('available', 'claimed', 'picked_up', 'expired', name='listing_status', native_enum=False), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('expires_at > prepared_at', name='ck_listing_expiry_after_prepared'),
    sa.CheckConstraint('servings > 0', name='ck_listing_servings_positive'),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_listings', schema=None) as batch_op:
        batch_op.create_index('ix_listings_donor_status', ['donor_id', 'status'], unique=False)
        batch_op.create_index('ix_listings_status_expires', ['status', 'expires_at'], unique=False)

    op.create_table('pickups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('servings_rescued', sa.Integer(), nullable=False),
    sa.CheckConstraint('servings_rescued > 0', name='ck_pickup_servings_positive'),
    sa.ForeignKeyConstraint(['listing_id'], ['food_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pickups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pickups_listing_id'), ['listing_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_pickups_recipient_id'), ['recipient_id'], unique=False)

    op.create_table('impact_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.Column('kg_saved', sa.Float(), nullable=False),
    sa.Column('co2e_kg', sa.Float(), nullable=False),
    sa.Column('people_served', sa.Integer(), nullable=False),
    sa.CheckConstraint('co2e_kg >= 0', name='ck_impact_co2e_nonneg'),
    sa.CheckConstraint('kg_saved >= 0', name='ck_impact_kg_nonneg'),
    sa.CheckConstraint('people_served >= 0', name='ck_impact_people_nonneg'),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impact_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impact_log_pickup_id'), ['pickup_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('impact_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impact_log_pickup_id'))

    op.drop_table('impact_log')
    with op.batch_alter_table('pickups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pickups_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_pickups_listing_id'))

    op.drop_table('pickups')
    with op.batch_alter_table('food_listings', schema=None) as batch_op:
        batch_op.drop_index('ix_listings_status_expires')
        batch_op.drop_index('ix_listings_donor_status')

    op.drop_table('food_listings')
    with op.batch_alter_table('donation_history', schema=None) as batch_op:
        batch_op.drop_index('ix_history_donor_date')

    op.drop_table('donation_history')
    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipients_type'))

    op.drop_table('recipients')
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donors_type'))

    op.drop_table('donors')
    # ### end Alembic commands ###
